#!/bin/sh

set -e

if [ "$1" = purge ]; then

  update-rc.d statsd remove >/dev/null || true

  rm -rf /var/run/statsd

  if dpkg-statoverride --list /var/run/statsd >/dev/null 2>&1; then
    dpkg-statoverride --remove /var/run/statsd
  fi

  deluser --system --quiet _statsd || true
  delgroup --system --quiet _statsd || true
fi
